Increase deployment target to macOS 13.0

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -17,8 +17,8 @@ if $is_recoveryos; then
 	fi
 	echo "\nNote: Genius only remains installed until restarting."
 else
-	if ! (( $(sw_vers -productVersion | cut -d "." -f 1) >= 11 )); then
-		echo "\nError: Genius requires macOS Big Sur 11 or later!\n" >&2
+	if ! (( $(sw_vers -productVersion | cut -d "." -f 1) >= 13 )); then
+		echo "\nError: Genius requires macOS Ventura 13 or later!\n" >&2
 		exit 1
 	fi
 fi
